export const SET_MAPCENTER = 'SET_MAPCENTER'
export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_CURRENT_USER_DEFAULT = 'SET_CURRENT_USER_DEFAULT'
export const SET_IS_EXPIRED = 'SET_IS_EXPIRED'
export const SET_MESSAGE = 'SET_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'

